GRANT USAGE ON SCHEMA public TO pml_java;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pml_java;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO pml_java;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO pml_java;

