version: '3'
services:
  postgresql:
    image: postgres:11.1
    container_name: music-library
    ports:
      - 5434:5432
    volumes:
      - ../sql:/fixtures
      - ./startup.sh:/docker-entrypoint-initdb.d/startup.sh
